import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import {
  decodeAcrosticCache,
  decodeAcrosticCacheRecord,
  type AcrosticCacheRecord,
} from "../lib/xwordinfo/acrostics.mts";

export type BundledAcrosticArchive = {
  availableDates: string[];
  cellCountByDate: Record<string, number>;
  latestDate: string;
  payloadByDate: Record<string, string>;
};

export function buildBundledAcrosticsArchive(
  records: readonly AcrosticCacheRecord[],
): BundledAcrosticArchive {
  const availableDates = records.map((record) => record.date);
  const payloadByDate: Record<string, string> = {};
  const cellCountByDate: Record<string, number> = {};

  for (const record of records) {
    payloadByDate[record.date] = record.acrostic;

    const { puzzle } = decodeAcrosticCacheRecord(record);
    cellCountByDate[record.date] = puzzle.gridNumbers.filter((number) => number > 0).length;
  }

  return {
    availableDates,
    cellCountByDate,
    latestDate: availableDates.at(-1) ?? "",
    payloadByDate,
  };
}

export function renderBundledAcrosticsArchiveModule(
  archive: BundledAcrosticArchive,
): string {
  return `// Generated by scripts/generate-acrostics-bundle.mts. Do not edit directly.

export type BundledAcrosticArchive = {
  availableDates: readonly string[];
  cellCountByDate: Readonly<Record<string, number>>;
  latestDate: string;
  payloadByDate: Readonly<Record<string, string>>;
};

export const bundledAcrosticDates: readonly string[] = ${JSON.stringify(archive.availableDates)};
export const latestBundledAcrosticDate = ${JSON.stringify(archive.latestDate)};
export const bundledAcrosticPayloadByDate: Readonly<Record<string, string>> = ${JSON.stringify(archive.payloadByDate)};
export const bundledAcrosticCellCountByDate: Readonly<Record<string, number>> = ${JSON.stringify(archive.cellCountByDate)};

export const bundledAcrosticArchive: BundledAcrosticArchive = {
  availableDates: bundledAcrosticDates,
  cellCountByDate: bundledAcrosticCellCountByDate,
  latestDate: latestBundledAcrosticDate,
  payloadByDate: bundledAcrosticPayloadByDate,
};
`;
}

export async function generateBundledAcrosticsArchive(options?: {
  inputFile?: string;
  outputFile?: string;
}): Promise<void> {
  const inputFile = path.resolve(
    options?.inputFile ?? "data/xwordinfo/acrostics.json.gz",
  );
  const outputFile = path.resolve(
    options?.outputFile ?? "lib/generated/acrostics-archive.ts",
  );
  const compressedArchive = await readFile(inputFile);
  const records = decodeAcrosticCache(compressedArchive);
  const archive = buildBundledAcrosticsArchive(records);
  const output = renderBundledAcrosticsArchiveModule(archive);

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, output, "utf8");
}

async function main() {
  await generateBundledAcrosticsArchive();
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
