import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import {
  decodeAcrosticCache,
  decodeAcrosticCacheRecord,
  type AcrosticCacheRecord,
} from "../lib/xwordinfo/acrostics.mts";

export type BundledAcrosticArchive = {
  availableDates: string[];
  cellCountByDate: Record<string, number>;
  latestDate: string;
  payloadByDate: Record<string, string>;
};

export type AcrosticArchiveStaticManifest = Omit<
  BundledAcrosticArchive,
  "payloadByDate"
>;

export function buildBundledAcrosticsArchive(
  records: readonly AcrosticCacheRecord[],
): BundledAcrosticArchive {
  const availableDates = records.map((record) => record.date);
  const payloadByDate: Record<string, string> = {};
  const cellCountByDate: Record<string, number> = {};

  for (const record of records) {
    payloadByDate[record.date] = record.acrostic;

    const { puzzle } = decodeAcrosticCacheRecord(record);
    cellCountByDate[record.date] = puzzle.gridNumbers.filter((number) => number > 0).length;
  }

  return {
    availableDates,
    cellCountByDate,
    latestDate: availableDates.at(-1) ?? "",
    payloadByDate,
  };
}

export function renderBundledAcrosticsArchiveModule(
  archive: BundledAcrosticArchive,
): string {
  return `// Generated by scripts/generate-acrostics-bundle.mts. Do not edit directly.

export type BundledAcrosticArchive = {
  availableDates: readonly string[];
  cellCountByDate: Readonly<Record<string, number>>;
  latestDate: string;
  payloadByDate: Readonly<Record<string, string>>;
};

export const bundledAcrosticDates: readonly string[] = ${JSON.stringify(archive.availableDates)};
export const latestBundledAcrosticDate = ${JSON.stringify(archive.latestDate)};
export const bundledAcrosticPayloadByDate: Readonly<Record<string, string>> = ${JSON.stringify(archive.payloadByDate)};
export const bundledAcrosticCellCountByDate: Readonly<Record<string, number>> = ${JSON.stringify(archive.cellCountByDate)};

export const bundledAcrosticArchive: BundledAcrosticArchive = {
  availableDates: bundledAcrosticDates,
  cellCountByDate: bundledAcrosticCellCountByDate,
  latestDate: latestBundledAcrosticDate,
  payloadByDate: bundledAcrosticPayloadByDate,
};
`;
}

export function buildAcrosticArchiveStaticManifest(
  archive: BundledAcrosticArchive,
): AcrosticArchiveStaticManifest {
  return {
    availableDates: archive.availableDates,
    cellCountByDate: archive.cellCountByDate,
    latestDate: archive.latestDate,
  };
}

export function renderAcrosticArchiveStaticManifestJson(
  manifest: AcrosticArchiveStaticManifest,
): string {
  return JSON.stringify(manifest);
}

export async function writeBundledAcrosticStaticAssets(
  records: readonly AcrosticCacheRecord[],
  outputDir: string,
): Promise<void> {
  const archive = buildBundledAcrosticsArchive(records);
  const manifest = buildAcrosticArchiveStaticManifest(archive);
  const normalizedOutputDir = path.resolve(outputDir);
  const puzzlesDir = path.join(normalizedOutputDir, "puzzles");

  await mkdir(normalizedOutputDir, { recursive: true });
  await rm(puzzlesDir, { force: true, recursive: true });
  await mkdir(puzzlesDir, { recursive: true });
  await writeFile(
    path.join(normalizedOutputDir, "manifest.json"),
    renderAcrosticArchiveStaticManifestJson(manifest),
    "utf8",
  );

  await Promise.all(
    records.map(async (record) => {
      const { puzzle } = decodeAcrosticCacheRecord(record);
      const outputFile = path.join(puzzlesDir, `${record.date}.json`);

      await writeFile(outputFile, JSON.stringify(puzzle), "utf8");
    }),
  );
}

export async function generateBundledAcrosticsArchive(options?: {
  inputFile?: string;
  outputFile?: string;
  staticAssetDir?: string;
}): Promise<void> {
  const inputFile = path.resolve(
    options?.inputFile ?? "data/xwordinfo/acrostics.json.gz",
  );
  const outputFile = path.resolve(
    options?.outputFile ?? "lib/generated/acrostics-archive.ts",
  );
  const compressedArchive = await readFile(inputFile);
  const records = decodeAcrosticCache(compressedArchive);
  const archive = buildBundledAcrosticsArchive(records);
  const output = renderBundledAcrosticsArchiveModule(archive);

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, output, "utf8");
  await writeBundledAcrosticStaticAssets(
    records,
    options?.staticAssetDir ?? "public/acrostics",
  );
}

async function main() {
  await generateBundledAcrosticsArchive();
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
